app/models.py
from app import db
import re


class User(db.Model):
    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), unique=True, nullable=False)
    spotify_id = db.Column(db.String(255), unique=True, nullable=False)
    birthdate = db.Column(db.DateTime, nullable=True)
    email = db.Column(db.String(255), unique=True)
    spotify_refresh_token = db.Column(db.String(255))
    num_of_contributions = db.Column(db.Integer, default=0)

    def __init__(self, username, spotify_id, birthdate, email, spotify_refresh_token):
        self.username = username
        self.spotify_id = spotify_id
        self.birthdate = birthdate
        self.email = email
        self.spotify_refresh_token = spotify_refresh_token
        self.num_of_contributions = -1

    def __repr__(self):
        return 'id: {}, username: {}, spotify_id: {}, birthdate: {}, email: {}' \
            .format(self.id, self.username, self.spotify_id, self.birthdate, self.email, self.num_of_contributions)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def toJSON(self):
        user = {
            "username": self.username,
            "spotify_id": self.spotify_id,
            "birthdate": self.birthdate,
            "email": self.email,
            "num_of_contributions": self.num_of_contributions,
            "spotify_refresh_token": self.spotify_refresh_token
        }
        return user

    @staticmethod
    def get_all():
        return User.query.all()

    @staticmethod
    def valid_email(email):
        emailPattern = re.compile("[^@]+@[^@]+\.[^@]+")
        if emailPattern.match(email) is None:
            return True
        return True

    @staticmethod
    def valid_username(username):
        usernamePattern = re.compile("^\w{1,255}$")
        if usernamePattern.match(username) is None:
            return True
        return True



class Lyrics(db.Model):
    __tablename__ = 'Lyrics'

    id = db.Column(db.Integer, primary_key=True)
    songtitle = db.Column(db.String(255), unique=False, nullable=False)
    artist = db.Column(db.String(255), unique=False, nullable=False)
    spotify_track_id = db.Column(db.String(255), unique=True, nullable=True)
    lyrics = db.Column(db.Text)
    timestamps = db.Column(db.Text)

    def __init__(self, songtitle, artist, spotify_track_id, lyrics, timestamps):
        self.songtitle = songtitle
        self.artist = artist
        self.spotify_track_id = spotify_track_id
        self.lyrics = lyrics
        self.timestamps = timestamps

    def __repr__(self):
        return 'id: {}, songtitle: {}, spotify_track_id: {}, lyrics: {}, timestamps: {}' \
            .format(self.id, self.songtitle, self.spotify_track_id, self.lyrics, self.timestamps)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def toJSON(self):
        lyric_sheet = {
            "songtitle": self.songtitle,
            "artist": self.artist,
            "spotify_track_id": self.spotify_track_id,
            "lyrics": self.lyrics,
            "timestamps": self.timestamps
        }
        return lyric_sheet

    @staticmethod
    def get_all():
        return Lyrics.query.all()
		
class LyricRating(db.Model):
    __tablename__ = 'LyricRating'

    id = db.Column(db.Integer, primary_key=True)
    rating = db.Column(db.Integer, nullable=False)

    lyrics_id = db.Column(db.Integer, db.ForeignKey('Lyrics.id', ondelete='CASCADE'), nullable=False)
    lyrics_id_rel = db.relationship('Lyrics', backref=db.backref('lyrics_id', passive_deletes=True),
                                    foreign_keys=lyrics_id)

    rater_id = db.Column(db.Integer, db.ForeignKey('Users.id', ondelete='CASCADE'), nullable=False)
    rater_id_rel = db.relationship('User', backref=db.backref('rater_id', passive_deletes=True), foreign_keys=rater_id)

    def __init__(self, rating, lyrics_id, rater_id):
        self.rating = rating
        self.lyrics_id = lyrics_id
        self.rater_id = rater_id

    def __repr__(self):
        return 'id: {}, rating: {}, lyrics_id: {}, rater_id: {}' \
            .format(self.id, self.rating, self.lyrics_id, self.rater_id)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def toJSON(self):
        rating = {
            "rating": self.rating,
            "lyrics_id": self.lyrics_id,
            "rater_id": self.rater_id
        }
        return rating

    @staticmethod
    def get_all():
        return LyricRating.query.all()


class RecentActivity(db.Model):
    __tablename__ = 'RecentActivity'

    id = db.Column(db.Integer, primary_key=True)
    spotify_track_id = db.Column(db.String(255), unique=False, nullable=False)
    spotify_id = db.Column(db.String(255), unique=False, nullable=False)

    def __init__(self, spotify_track_id, spotify_id):
        self.spotify_track_id = spotify_track_id
        self.spotify_id = spotify_id

    def __repr__(self):
        return 'id: {}, spotify_track_id: {}, spotify_id: {}' \
            .format(self.id, self.spotify_track_id, self.spotify_id)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def toJSON(self):
        rating = {
            "spotify_track_id": self.spotify_track_id,
            "spotify_id": self.spotify_id,
            "username": db.session.query(User).filter_by(spotify_id=self.spotify_id).first().username
        }
        return rating

    @staticmethod
    def get_all():
        return RecentActivity.query.all()

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from config import app_config

# db variable initialization
db = SQLAlchemy()

def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(app_config['production'])
    app.config.from_pyfile('../config.py')
    db.app = app
    db.init_app(app)

    from app import models

    migrate = Migrate(app, db)
    
    from .views import views_blueprint
    app.register_blueprint(views_blueprint)

    from .usersBp import users_blueprint
    app.register_blueprint(users_blueprint, url_prefix="/users")

    from .lyricsBp import lyrics_blueprint
    app.register_blueprint(lyrics_blueprint, url_prefix="/lyrics")

    from .lyricratingBp import lyricrating_blueprint
    app.register_blueprint(lyricrating_blueprint, url_prefix="/lyricrating")

    return app

app/views.py
from flask import Blueprint, render_template, redirect, request, make_response, url_for, jsonify
import urllib
from app.spotifyapi import *
import app
from app import db
from app.models import *

views_blueprint = Blueprint('views', __name__)

@views_blueprint.route("/")
def index():
    auth_url = get_auth_url()
    return render_template('index.html', auth_url=auth_url)


@views_blueprint.route("/lyrics")
def lyrics():
    return render_template('lyrics.html')


@views_blueprint.route("/users")
def users():
    return render_template("users.html")


@views_blueprint.route("/songs")
def songs():
    return render_template("songs.html")


@views_blueprint.route("/contact")
def contact():
    return render_template("contact.html")

@views_blueprint.route("/activity")
def activity():
    return render_template("activity.html")


@views_blueprint.route("/login")
def login():
    code = request.args['code']

    tokens = get_tokens(code)

    if "error" in tokens:
        return redirect(url_for("views.index"))

    access_token = tokens["access_token"]
    refresh_token = tokens["refresh_token"]
    token_type = tokens["token_type"]
    ##expires_in = tokens["expires_in"]

    app.usersBp.login(access_token, refresh_token)

    resp = make_response(redirect(url_for("views.index")))
    resp.set_cookie('access_token', access_token)
    resp.set_cookie('refresh_token', refresh_token)

    return resp

@views_blueprint.route("/currSong", methods=['POST'])
def get_current_track_id():
   access_token = request.cookies.get('access_token')
   track = get_current_track(access_token)

   if "error" in track:
       return jsonify({'result': False, 'error': track['error']['message']})

   spotify_track_id = track['item']['id']

   track = get_track(access_token, spotify_track_id)

   lyrics_page = db.session.query(Lyrics).filter_by(spotify_track_id=spotify_track_id).first()
   if lyrics_page is None:
       track_name = track['name']
       artist = get_artists_by_track(track)
       lyrics_page = Lyrics(spotify_track_id, artist, track_name, "", "")
       lyrics_page.save()

   return jsonify({'result': True, 'error': "", 'lyric_page': lyrics_page.toJSON()})

app/templates/activity.html
<!DOCTYPE HTML>
<html>

<head>
    <meta name="description" content="Real Time Lyrics" />
    <meta name="keywords" content="website keywords, website keywords" />
    <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
    <link rel="stylesheet" type="text/css" href="#" title="style" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="../static/login.js"></script>
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">

          <h1><a href="{{ url_for('views.index') }}">LiveLyrics</a></h1>
          <h2>Lyrics in Real Time.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">

          <li class=><a href="#">Home</a></li>
          <li><a href="{{ url_for('views.songs') }}">Users</a></li>
          <li><a href="{{ url_for('views.users') }}">Songs</a></li>
          <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSfkYm6pUmVJ7It-f96yoRxCMMzvktP9RRao0aAWooRUGMQW7Q/viewform?usp=sf_link" >Contact Us</a></li>
            <li class="selected"><a href="{{ url_for('views.activity')}}">Recent Activity</a></li>
            <li><a id = "loginMenu" href="#">Login</a></li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <div class="sidebar">

      </div>
      <div id="content">

        <h1>Recent activity</h1>


      </div>

      <div id="activity-feed">
      </div>
      </div>
    </div>
  </div>

  <script type="text/javascript" src="../static/activity.js"></script>
</body>
</html>

app/templates/contact.html
<!DOCTYPE HTML>
<html>

<head>

  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="../static/style.css" title="style" />
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">
         
          <h1><a href="{{ url_for('views.index') }}">LiveLyrics</a></h1>
          <h2>Lyrics in Real Time.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
   
		  <li class="selected"><a href="#">Home</a></li>
          <li><a href="{{ url_for('views.lyrics') }}">Add Lyrics</a></li>
           <li><a href="{{ url_for('views.songs') }}">Users</a></li>
          <li><a href="{{ url_for('views.users') }}">Songs</a></li>
          <li><a href="{{ url_for('views.contact') }}">Contact Us</a></li>
        </ul>
      </div>
    </div>
    <div id="content_header"></div>
    <div id="site_content">

      <div id="content">
        
        <h1>Contact Us</h1>
        <p> Thank you for leaving feedback, please complete the form below</p>
        <form action="#" method="post">
          <div class="form_settings">
            <p><span>Email Address</span><input class="contact" type="text" name="your_email" value="" /></p>
            <p><span>Message</span><textarea class="contact textarea" rows="8" cols="50" name="your_enquiry"></textarea></p>
            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="contact_submitted" value="submit" /></p>
          </div>
        </form>
 
      </div>
    </div>

  </div>
</body>
</html>

app/templates/error.html
<!DOCTYPE html>
<html>
<body>

<h1>Error has occurred</h1>

<p>ERROR: {{ error }}</p>

</body>
</html>

app/templates/index.html
<!DOCTYPE HTML>
<html>

<head>
    <meta name="description" content="Real Time Lyrics" />
    <meta name="keywords" content="website keywords, website keywords" />
    <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
    <link rel="stylesheet" type="text/css" href="../static/style.css" title="style" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="../static/login.js"></script>
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">
         
          <h1><a href="{{ url_for('views.index') }}">LiveLyrics</a></h1>
          <h2>Lyrics in Real Time.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
         
          <li class="selected"><a href="#">Home</a></li>
           <li><a href="{{ url_for('views.songs') }}">Users</a></li>
          <li><a href="{{ url_for('views.users') }}">Songs</a></li>
          <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSfkYm6pUmVJ7It-f96yoRxCMMzvktP9RRao0aAWooRUGMQW7Q/viewform?usp=sf_link" >Contact Us</a></li>
            <li><a href="{{ url_for('views.activity')}}">Recent Activity</a></li>
            <li><a id = "loginMenu" href="{{ auth_url}}">Login</a></li>
             <li><a id = "logoutMenu" href="#" onclick="">Logout</a></li>
            <li>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <div class="sidebar">
  
      </div>
      <div id="content">
    
        <h1>Welcome to the Live Lyrics</h1>
        <p>Connect your Spotify account and experience live lyrics while listening to a song. </p>
		<p>View lyrics from users around the world and add your own. </p>
          <p id="access_token"></p>
          <script type="text/javascript">
              var access_token = getCookie("access_token");
              if (access_token) {

                var jsonob = {
                    "access_token": localStorage.getItem("access_token")
                }

                $.ajax({
                    type: "POST",
                    url: "http://18.219.242.5/users/info/me",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonob, null, '\t')
                })
                .done(function( msg ) {
                console.log(JSON.stringify(msg));
                document.getElementById("access_token").innerHTML = "You are logged in as: " + msg.user.email;
                })
                .fail(function( jqXHR, textStatus ) {
                    alert( "Request failed: " + textStatus );
                })
              }

          </script>

      </div>

    </div>
  </div>

</body>
</html>

app/templates/lyrics.html
<!DOCTYPE HTML>
<html>

<head>

  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="../static/style.css" title="style" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  
 
<style>
div.stars {
  width: 270px;
  display: inline-block;
    right: 100px;
}

input.star {
	display: none;
	right: 100px;
 }

label.star {
  float: right;
  padding: 10px;
  font-size: 36px;
  color: #444;
  transition: all .2s;

}

input.star:checked ~ label.star:before {
  content: '\2605';
  color: #FD4;
  transition: all .25s;
}


input.star-1:checked ~ label.star:before { color: #F62; }

label.star:hover { transform:  scale(1.3); }

label.star:before {
  content: '\2605';
}
</style>
 
</head>

<body >
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">
    
          <h1><a href="{{ url_for('views.index') }}">LiveLyrics</a></h1>
          <h2>Lyrics in Real Time.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
        
			<li class="selected"><a href="#">Home</a></li>
         <li><a href="{{ url_for('views.songs') }}">Users</a></li>
          <li><a href="{{ url_for('views.users') }}">Songs</a></li>
          <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSfkYm6pUmVJ7It-f96yoRxCMMzvktP9RRao0aAWooRUGMQW7Q/viewform?usp=sf_link" >Contact Us</a></li>
             <li><a href="{{ url_for('views.activity')}}">Recent Activity</a></li>
        </ul>
      </div>
    </div>
    <div id="content_header"></div>
    <div id="site_content">
      
      <div id="content">
  
        <form action="http://18.219.242.5/lyrics/edit" id="songEditForm">
          <div class="form_settings">

            <p style="padding-bottom: 4px"><span>New song name:</span><input id="song-title-input" type="text" name="songtitle"><br></p>
            <p style="padding-bottom: 4px"><span>Lyrics:</span><input id="lyrics-input" type="text" name="lyrics" class="lyricsInputTest"><br></p>
            <p style="padding-bottom: 4px"><span>Track id:</span><input id="spotify-track-id-input" type="text" name="spotify_track_id" class="lyricsTrackIDTest"><br></p>
            <p style="padding-bottom: 4px"><span>Timestamps:</span><input id="timestamps-input" type="text" name="timestamps" class="lyricsTimestampsTest"><br></p>
						<p style="padding-bottom: 4px"><span></span><input id="access_token-input" type="hidden" name="access_token" class="accessToken"><br></p>
            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="lyrics_submitted" value="submit"/></p>
		
          </div>
        </form>


          </div>
        </form>
      </div>
    </div>
 
  </div>
    <script type="text/javascript" src="../static/lyrics.js"></script>
	
	<div class="stars" style="margin-left: 450px;">
	<form class = "rating" method = "POST" >
    <input hidden class="star " id="star-5" type="radio" name="rating" value="5"/>
    <label hidden class="star " for="star-5"></label>
    <input class="star " id="star-4" type="radio" name="rating" value="4"/>
    <label class="star " for="star-4" ></label>
    <input class="star " id="star-3" type="radio" name="rating" value="3"/>
    <label class="star " for="star-3"></label>
    <input class="star " id="star-2" type="radio" name="rating" value="2"/>
    <label class="star " for="star-2"></label>
    <input class="star " id="star-1" type="radio" name="rating" value="1"/>
    <label class="star " for="star-1" ></label>
	
	
  </form>
  
	<button type="button" style="margin-left: 100px" onclick="sendRating()">Submit Rating</button>
 
</div>
<script>
 
        function loadRatings() {
			var trackid = document.getElementsByName('spotify_track_id')[0].value;
			var http = new XMLHttpRequest();
			console.log(trackid);
			var data = {
				"lyric_id": trackid
			}
			console.log(data);
			http.onreadystatechange = function() {
				if (http.readyState == XMLHttpRequest.DONE) {
					var result = JSON.parse(http.responseText);
					console.log(result);
					if (result.result == false) {
						console.log("No ratings found");
					}
					else {
						var rating = result.avgRating;
						console.log("Average rating of " + rating + " found");
						if (rating > 0) {
							document.getElementsByName('rating')[4].checked = true;
						}
						if (rating > 1) {
							document.getElementsByName('rating')[3].checked = true;
						}
						if (rating> 2) {
							document.getElementsByName('rating')[2].checked = true;
						}
						if (rating> 3) {
							document.getElementsByName('rating')[1].checked = true;
						}
						if (rating > 4) {
							document.getElementsByName('rating')[0].checked = true;
						}						
					}
				}
			}
			http.open("POST", 'http://18.219.242.5/lyricrating/avgRating', true);
			http.setRequestHeader("Content-type", "application/json");
			console.log(http);
			http.send(JSON.stringify(data, null, '\t') );
		
		}
			

		setTimeout(function() { loadRatings(); }, 2000);
	</script>

	<script>
	
		function sendRating() {	
			var http = new XMLHttpRequest();
			http.onreadystatechange = function() {
				if (http.readyState == XMLHttpRequest.DONE) {
					var result = JSON.parse(http.responseText);
					console.log(result);
					var userid = result.User.spotify_id;
					console.log(userid);	
					var trackid = document.getElementsByName('spotify_track_id')[0].value;	
					console.log(trackid);
						
					for (i = 0; i < document.getElementsByName('rating').length; i++) {

						if(document.getElementsByName('rating')[i].checked == true) {
							
							var ratingValue = document.getElementsByName('rating')[i].value;
														
							var data2 = {
								"rating": ratingValue,
								"lyric_id": trackid,
								"rater_id": userid
							}
							console.log(data2);
							var http2 = new XMLHttpRequest();
							
							http2.onreadystatechange = function() {
								if (http2.readyState == XMLHttpRequest.DONE) {
									var result = JSON.parse(http2.responseText);
									console.log(result);
								}
							}
							
							
							http2.open("POST", 'http://18.219.242.5/lyricrating/rate', true);
							http2.setRequestHeader("Content-type", "application/json");
							console.log(http2);
							http2.send(JSON.stringify(data2, null, '\t') );	
							
								
						
						}
						
						
					}	
					return;
				}
			}
			http.open("POST", 'http://18.219.242.5/users/getUser', true);
			http.setRequestHeader("Content-type", "application/json");
			var token = document.getElementsByName('access_token')[0].value;
			console.log(token);
			var data = {
				"access_token" : token
			}
			console.log(data);
			http.send(JSON.stringify(data, null, '\t') );

	} 

</script>

<script>

</script>


</body>
</html>

app/templates/results.html
<!DOCTYPE HTML>
<html>

<head>
 
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="../static/style.css" title="style" />
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">

          <h1><a href="{{ url_for('views.index') }}">LiveLyrics</a></h1>
          <h2>Lyrics in Real Time.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
 
		  <li class="selected"><a href="#">Home</a></li>
           <li><a href="{{ url_for('views.songs') }}">Users</a></li>
          <li><a href="{{ url_for('views.users') }}">Songs</a></li>
          <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSfkYm6pUmVJ7It-f96yoRxCMMzvktP9RRao0aAWooRUGMQW7Q/viewform?usp=sf_link" >Contact Us</a></li>
             <li><a href="{{ url_for('views.activity')}}">Recent Activity</a></li>
        </ul>
      </div>
    </div>
    <div id="content_header"></div>
    <div id="site_content">
      
      <div id="content">
  
        
        <h1>Top Users</h1>
        <p> .</p>
      </div>
    </div>

  </div>
</body>
</html>

app/templates/songs.html
<!DOCTYPE HTML>
<html>

<head>

  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="../static/style.css" title="style" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">

          <h1><a href="{{ url_for('views.index') }}">LiveLyrics</a></h1>
          <h2>Lyrics in Real Time.</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
  
		  <li class="selected"><a href="#">Home</a></li>
          <li><a href="{{ url_for('views.songs') }}">Users</a></li>
          <li><a href="{{ url_for('views.users') }}">Songs</a></li>
          <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSfkYm6pUmVJ7It-f96yoRxCMMzvktP9RRao0aAWooRUGMQW7Q/viewform?usp=sf_link" >Contact Us</a>
             <li><a href="{{ url_for('views.activity')}}">Recent Activity</a></li>
        </ul>
      </div>
    </div>
    <div id="content_header"></div>
    <div id="site_content">

      <div id="content">
     
        <form action="http://18.219.242.5/lyrics/search" id="songsForm">
          <div class="form_settings">
            <p><span>Search for songs by name:</span><input type="text" name="song"></p>
            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="userInfo_submitted" value="submit"/></p>
          </div>
        </form>

       <!-- <p> or <a href="#" id="sync-link">Select the song you're listening to on your phone!</a><br> </p>
        -->
	<p> or <a href="#" id="sync-link">Spotify current playing track lyric page!</a><br> </p>
      
	</div>

      <div class="song-list">
      </div>
    </div>

  </div>

  <script type="text/javascript" src="../static/songs.js"></script>
</body>
</html>

app/templates/users.html
<!DOCTYPE HTML>
<html>

<head>
 
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" type="text/css" href="../static/style.css" title="style" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">

          <h1><a href="{{ url_for('views.index') }}">LiveLyrics</a></h1>
          <h2>Lyrics in Real Time.</h2>

        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
 
		  <li class="selected"><a href="#">Home</a></li>
           <li><a href="{{ url_for('views.songs') }}">Users</a></li>
          <li><a href="{{ url_for('views.users') }}">Songs</a></li>
          <li><a href="https://docs.google.com/forms/d/e/1FAIpQLSfkYm6pUmVJ7It-f96yoRxCMMzvktP9RRao0aAWooRUGMQW7Q/viewform?usp=sf_link">Contact Us</a></li>
             <li><a href="{{ url_for('views.activity')}}">Recent Activity</a></li>
        </ul>
      </div>
    </div>
    <div id="content_header"></div>
    <div id="site_content">
      
      <div id="content">
  
          <form action="http://18.219.242.5/users/info" id="userForm">
            <div class="form_settings">
              <p><span>Search for users:</span><input type="text" name="username"><br></p>
              <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="userSearch_submitted" value="submit" size="20"/></p>
            </div>
          </form>

      <div id="searchResults"></div>
      </div>

      <div class="user-box" style="display:none">
      </div>


      <div id="editFormID">
        <form action="http://18.219.242.5/users/edit" id="editForm">
          <div class="form_settings">
            <p> Edit your username! Inputs in the following fields will become your new parameters when you submit</p><br>
            <p style="padding-bottom: 4px"><span>New Username:</span><input type="text" name="username" class="newUserTest"><br></p>
            <p style="padding-bottom: 4px"><span>New Birthdate:</span><input type="date" name="birthdate" class="newBirthdateTest"><br></p>
            <p style="padding-bottom: 4px"><span>New E-mail:</span><input type="text" name="email" class="emailTest"><br></p>
            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="userInfo_submitted" value="submit" size="20"/></p>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script type="text/javascript" src="../static/users.js"></script>
</body>
</html>